cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/black_mirror; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/clube_da_luta; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/downton_abbey; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/house; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/house_of_cards; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/juno; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/lobo_de_wallstreet; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/missao_impossivel; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/pulp_fiction; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/quebrando_a_banca; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/sex_and_the_city; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/sexto_sentido; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/star_trek; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/stranger_things; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/suits; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/the_avengers; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/toy_story_3; convert thumbnail.png -quality 85 thumbnail.jpg
cd /home/arthur/Projects/chofra/chofra-netflix/app/images/movies/truque_de_mestre; convert thumbnail.png -quality 85 thumbnail.jpg

